-- AlterTable
ALTER TABLE "FollowUpTask" ADD COLUMN IF NOT EXISTS "meetingLink" TEXT NOT NULL DEFAULT '';
ALTER TABLE "FollowUpTask" ADD COLUMN IF NOT EXISTS "calendarEventId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "FollowUpTask" ADD COLUMN IF NOT EXISTS "calendarSyncStatus" TEXT NOT NULL DEFAULT '';
ALTER TABLE "FollowUpTask" ADD COLUMN IF NOT EXISTS "syncGoogleCalendar" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "FollowUpTask" ADD COLUMN IF NOT EXISTS "notifyEmail" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "FollowUpTask" ADD COLUMN IF NOT EXISTS "notifyWhatsApp" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "FollowUpTask" ADD COLUMN IF NOT EXISTS "notificationLog" JSONB NOT NULL DEFAULT '{}';
