ALTER TABLE "LibBook" ADD COLUMN IF NOT EXISTS "vendorId" TEXT;
ALTER TABLE "LibBook" ADD COLUMN IF NOT EXISTS "deweyDecimal" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LibBook" ADD COLUMN IF NOT EXISTS "purchaseDate" DATE;
ALTER TABLE "LibBook" ADD COLUMN IF NOT EXISTS "purchasePrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LibBook" ADD COLUMN IF NOT EXISTS "invoiceNo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LibBook" ADD COLUMN IF NOT EXISTS "marcData" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "LibBook" ADD COLUMN IF NOT EXISTS "language" TEXT NOT NULL DEFAULT 'English';
ALTER TABLE "LibBook" ADD COLUMN IF NOT EXISTS "pageCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "LibBookCopy" ADD COLUMN IF NOT EXISTS "condition" TEXT NOT NULL DEFAULT 'GOOD';
ALTER TABLE "LibBookCopy" ADD COLUMN IF NOT EXISTS "purchasePrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "LibBookCopy" ADD COLUMN IF NOT EXISTS "barcodePrinted" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS "LibBook_vendorId_idx" ON "LibBook"("vendorId");
ALTER TABLE "LibBook" ADD CONSTRAINT "LibBook_vendorId_fkey" FOREIGN KEY ("vendorId") REFERENCES "LibVendor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
