services:
  - type: web
    name: 360schoolerp-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run prisma:migrate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
