-- Add approval workflow status for fine levies
DO $$ BEGIN
  ALTER TYPE "FeeFineLevyStatus" ADD VALUE 'PENDING_APPROVAL';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "FeeFineLevy" ADD COLUMN IF NOT EXISTS "sectionName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "FeeFineLevy" ADD COLUMN IF NOT EXISTS "pendingApproverRole" TEXT NOT NULL DEFAULT '';
ALTER TABLE "FeeFineLevy" ADD COLUMN IF NOT EXISTS "pendingApproverName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "FeeFineLevy" ADD COLUMN IF NOT EXISTS "pendingApproverEmail" TEXT NOT NULL DEFAULT '';
ALTER TABLE "FeeFineLevy" ADD COLUMN IF NOT EXISTS "requestedBy" TEXT NOT NULL DEFAULT '';
ALTER TABLE "FeeFineLevy" ADD COLUMN IF NOT EXISTS "approvedBy" TEXT NOT NULL DEFAULT '';
ALTER TABLE "FeeFineLevy" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
ALTER TABLE "FeeFineLevy" ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT NOT NULL DEFAULT '';
