ALTER TABLE "FeeOtherChargeRequest" ADD COLUMN IF NOT EXISTS "totalDueFees" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "FeeOtherChargeRequest" ADD COLUMN IF NOT EXISTS "pendingApproverRole" TEXT NOT NULL DEFAULT '';
ALTER TABLE "FeeOtherChargeRequest" ADD COLUMN IF NOT EXISTS "pendingApproverName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "FeeOtherChargeRequest" ADD COLUMN IF NOT EXISTS "pendingApproverEmail" TEXT NOT NULL DEFAULT '';
