export type ExpenseCategorySeed = {
  group: string;
  code: string;
  name: string;
  heads: string[];
};

export const EXPENSE_CATEGORY_SEED: ExpenseCategorySeed[] = [
  {
    group: 'Academic Expenses',
    code: 'ACADEMIC',
    name: 'Academic Expenses',
    heads: [
      'Books & Stationery',
      'Laboratory Materials',
      'Examination Expenses',
      'Printing & Photocopy',
      'Smart Class Content',
      'Library Purchases',
      'Educational Software',
      'Student Activity Expenses',
      'Competition Expenses',
    ],
  },
  {
    group: 'Employee Expenses',
    code: 'EMPLOYEE',
    name: 'Employee Expenses',
    heads: [
      'Salaries',
      'Wages',
      'Overtime',
      'Incentives',
      'Bonus',
      'PF Contribution',
      'ESI Contribution',
      'Professional Tax',
      'Staff Welfare',
      'Medical Reimbursement',
      'Staff Training',
      'Uniform',
      'Recruitment Expenses',
      'Employee Travel',
      'Staff Accommodation',
    ],
  },
  {
    group: 'Administration',
    code: 'ADMIN',
    name: 'Administration',
    heads: [
      'Office Stationery',
      'Office Equipment',
      'Printer & Toner',
      'Courier Charges',
      'Documentation',
      'Office Consumables',
      'Xerox',
      'Postage',
    ],
  },
  {
    group: 'Infrastructure',
    code: 'INFRA',
    name: 'Infrastructure',
    heads: [
      'Building Rent',
      'Building Repairs',
      'Painting',
      'Plumbing',
      'Electrical Maintenance',
      'Carpentry',
      'Civil Work',
      'Furniture Purchase',
      'Furniture Repair',
      'School Renovation',
      'Campus Beautification',
    ],
  },
  {
    group: 'Utility Expenses',
    code: 'UTILITY',
    name: 'Utility Expenses',
    heads: [
      'Electricity Bill',
      'Water Bill',
      'Gas Bill',
      'Internet',
      'Telephone',
      'Mobile Bills',
      'Generator Fuel',
      'Solar Maintenance',
    ],
  },
  {
    group: 'IT & Technology',
    code: 'IT',
    name: 'IT & Technology',
    heads: [
      'ERP Subscription',
      'Website Hosting',
      'Domain Renewal',
      'Cloud Hosting',
      'Software Licenses',
      'CCTV Maintenance',
      'Computer Repairs',
      'Laptop Purchase',
      'Printer Purchase',
      'Networking Equipment',
      'AI Tool Subscription',
      'Cybersecurity',
    ],
  },
  {
    group: 'Transport',
    code: 'TRANSPORT',
    name: 'Transport',
    heads: [
      'Fuel',
      'Driver Salary',
      'Vehicle Maintenance',
      'Insurance',
      'Tyres',
      'Bus Permit',
      'Fitness Certificate',
      'Pollution Certificate',
      'GPS Subscription',
      'Toll Charges',
      'Parking',
      'Washing',
    ],
  },
  {
    group: 'Hostel',
    code: 'HOSTEL',
    name: 'Hostel',
    heads: [
      'Food Purchase',
      'Grocery',
      'Vegetables',
      'Milk',
      'Gas Cylinder',
      'Kitchen Equipment',
      'Housekeeping',
      'Laundry',
      'Hostel Repairs',
      'Security',
    ],
  },
  {
    group: 'Library',
    code: 'LIBRARY',
    name: 'Library',
    heads: ['Books', 'Journals', 'Newspapers', 'Digital Library', 'Library Software'],
  },
  {
    group: 'Laboratory',
    code: 'LAB',
    name: 'Laboratory',
    heads: ['Chemicals', 'Glassware', 'Equipment', 'Consumables', 'Safety Equipment', 'Calibration'],
  },
  {
    group: 'Sports',
    code: 'SPORTS',
    name: 'Sports',
    heads: [
      'Sports Equipment',
      'Ground Maintenance',
      'Tournament Fees',
      'Coaching',
      'Sports Uniform',
    ],
  },
  {
    group: 'Cultural Activities',
    code: 'CULTURAL',
    name: 'Cultural Activities',
    heads: [
      'Stage Decoration',
      'Sound System',
      'Lighting',
      'Costume',
      'Music Equipment',
      'Photography',
      'Videography',
    ],
  },
  {
    group: 'Marketing',
    code: 'MARKETING',
    name: 'Marketing',
    heads: [
      'Newspaper Advertisement',
      'Social Media Ads',
      'Hoardings',
      'School Brochures',
      'Flyers',
      'Digital Marketing',
      'Branding Material',
    ],
  },
  {
    group: 'Legal & Compliance',
    code: 'LEGAL',
    name: 'Legal & Compliance',
    heads: [
      'Audit Fees',
      'CA Fees',
      'Legal Consultancy',
      'ROC Filing',
      'GST Filing',
      'Licenses',
      'Government Fees',
    ],
  },
  {
    group: 'Medical',
    code: 'MEDICAL',
    name: 'Medical',
    heads: ['First Aid', 'Medical Camp', 'Doctor Visit', 'Medicines', 'Sanitization'],
  },
  {
    group: 'Housekeeping',
    code: 'HOUSEKEEPING',
    name: 'Housekeeping',
    heads: ['Cleaning Materials', 'Pest Control', 'Waste Management', 'Garden Maintenance'],
  },
  {
    group: 'Security',
    code: 'SECURITY',
    name: 'Security',
    heads: ['Security Guards', 'CCTV', 'Fire Safety', 'Security Equipment'],
  },
  {
    group: 'Miscellaneous',
    code: 'MISC',
    name: 'Miscellaneous',
    heads: ['Donations', 'Hospitality', 'Guest Expenses', 'Festival Expenses', 'Contingency', 'Other Expenses'],
  },
];

export const EXPENSE_DEPARTMENTS = [
  'Academic',
  'Administration',
  'Accounts',
  'Transport',
  'Hostel',
  'Library',
  'Sports',
  'IT',
  'Maintenance',
  'HR',
  'Marketing',
  'General',
];

export const EXPENSE_CAMPUSES = ['Main Campus', 'North Campus', 'South Campus', 'Junior Wing'];
export const EXPENSE_BRANCHES = ['Main Branch', 'City Branch', 'Suburban Branch'];

export const EXPENSE_ASSET_TYPES = [
  'Building',
  'Bus',
  'Computer',
  'Smart Board',
  'Furniture',
  'Laboratory Equipment',
  'Air Conditioner',
];
